//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WikipediaProgromistsWF.InfoText {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WikipediaProgromistsWF.InfoText.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разработчик компилятора для Pascal, благодаря которому компиляция программы сократилась до нескольких секунд.
        ///
        ///Первая версия компилятора была написана под DOS. Позже компилятор был встроен в среду Turbo Pascal. Благодаря компилятору Хейлсберга продуктивность работы в сфере IT выросла в несколько раз.
        ///
        ///Позже Хейлсберг возглавил команду, разработавшую Borland Delphi. И здесь также особое внимание было уделено быстродействию.  Сегодня Delphi – один из самых популярных языков..
        /// </summary>
        internal static string AndersHalesbergInfoText {
            get {
                return ResourceManager.GetString("AndersHalesbergInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создатель языка C++ (улучшенной версии C).
        ///
        ///Сегодня язык программирования C++ изучают студенты практически в любом ВУЗе, он давно стал одним из базовых прикладных языков. Синтаксис языка C используется в PHP и других современных языках программирования. Доработки от Бьерна Страуструпа оказались настолько хороши, что сегодня, когда говорят «Си», о базовой версии языка даже не вспоминают.
        ///
        ///В наше время программист читает лекции в нескольких ВУЗах, сотрудничает с Morgan Stanley..
        /// </summary>
        internal static string BjörnStraustrupInfoText {
            get {
                return ResourceManager.GetString("BjörnStraustrupInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автор протокола BitTorrent, благодаря которому стала возможной супербыстрая загрузка файлов из сети.
        ///
        ///Торрент популярен во всем мире. Число пользователей BitTorrent  оценивается в 250 млн человек. Через торренты скачиваются огромные объемы информации. К сожалению, возможности торрентов активно используют «пираты»..
        /// </summary>
        internal static string BramCohenInfoText {
            get {
                return ResourceManager.GetString("BramCohenInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разработчик JavaScript. Этот язык считается одним из стандартов в WEB-программировании.
        ///
        ///Принимал участие в создании компании Mozilla и браузера Firefox. Занимал пост СЕО. Уволился после скандала, связанного с его позицией по вопросам гей-браков (Брендан – активный участник движения за их запрет в Калифорнии)..
        /// </summary>
        internal static string BrendAnIkeInfoText {
            get {
                return ResourceManager.GetString("BrendAnIkeInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автор уникальной монографии «Искусство программирования», которая стала учебником и настольной книгой программистов во всем мире. Почетный профессор в Стенфорде.
        ///
        ///Академические работы Кнута – это огромный труд, охватывающий практически все направления в программировании, начиная от структур данных и заканчивая анализом алгоритмов. Последнее направление Крут создал лично. Кроме теории в монографии содержится множество примеров на языке Ассемблер.
        ///
        ///Ведущие разработчики Google, Facebook других крупных прое [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string DonaldKnutInfoText {
            get {
                return ResourceManager.GetString("DonaldKnutInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автор объектно-ориентированного языка Java.
        ///
        ///Еще одна крупная разработка — NEWS, система распределения вычислений в компьютерных сетях. Перечень проектов, над которыми он работал, обширен. Здесь и системы анализа результатов спутниковой телеметрии, и редактор текстов Emacs, и многое другое. Некоторое время Гослинг принимал участие в разработке алгоритмов Google, в последнее время занимается разработкой программного обеспечения для подводных исследований..
        /// </summary>
        internal static string JamesGoslingInfoText {
            get {
                return ResourceManager.GetString("JamesGoslingInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Один из основателей компании id Software. Известность получил как автор легендарной компьютерной игры Doom.
        ///
        ///Идея создания Doom пришла в голову Джона во время корпоративной партии D&amp;D. В то время в компании подобные партии проводили регулярно. И часто на них Джон выполнял роль гейм-мастера.
        ///
        ///При создании Doom Джон Кармак первым реализовал оригинальные 3D-трюки, которые применяют в компьютерных играх до сих пор..
        /// </summary>
        internal static string JohnCarmackInfoText {
            get {
                return ResourceManager.GetString("JohnCarmackInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Финно-американский программист, создатель операционной системы Linux, на которой работают дата-центры и множество компьютеров во всем мире.
        ///
        ///Благодаря Торвальдсу, убежденному стороннику freeware (свободно распространяемого софта), в индустрии, где крутятся огромные деньги и все пропитано коммерцией и паранойей, появилась полностью бесплатная операционная система с открытым кодом.  Сегодня в разработке и обновлениях Линукс участвуют тысячи программистов.
        ///
        ///В профессиональной среде Линус Торвальдс известен [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string LinusTorvaldsInfoText {
            get {
                return ResourceManager.GetString("LinusTorvaldsInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Американский программист, разработчик социальной сети Facebook.
        ///
        ///Это имя широко известно за пределами профессиональной среды. Цукерберг – фигура публичная. С его социальной сетью в последнее время связано множество скандалов. Тем не менее, проект продолжает успешно развиваться.
        ///
        ///Цукерберг убежден, что наиболее эффективны – небольшие команды. Они могут работать плодотворнее, чем крупные коллективы. Потому в обслуживании огромной социальной сети задействовано всего лишь 10 000 человек в мире..
        /// </summary>
        internal static string MarkZuckerbergInfoText {
            get {
                return ResourceManager.GetString("MarkZuckerbergInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автор HTTP протокола, на котором основана работа Интернет. Единственный программист, возведенный в звание рыцаря.
        ///
        ///Сегодня он возглавляет общественную организацию «Альянс за доступный интернет», основная цель которой – доступный и быстрый интернет для всех. Организация пользуется поддержкой крупных корпораций – Google, Microsoft, Facebook..
        /// </summary>
        internal static string SirTimBernersLeeInfoText {
            get {
                return ResourceManager.GetString("SirTimBernersLeeInfoText", resourceCulture);
            }
        }
    }
}
